ftp:
  # ftp配置
  host: 211.157.146.9
  port: 21
  username: ftp002
  password: hisign
  # binary二进制 passiveMode被动模式 delay读取文件间隔(s)
  options: password=${ftp.password}&binary=true&passiveMode=true&delay=60s
  url: ftp://${ftp.username}@${ftp.host}:${ftp.port}${ftp.remote-dir}?${ftp.options}
  # ftp远程起始目录
  remote-dir: /
  # 本地下载目录
  local-dir: /data

# 后台运行进程
camel:
  springboot:
    main-run-controller: true

# es配置
spring:
  data:
    elasticsearch:
      # 集群名称
      cluster-name: my-application
      # 集群节点地址列表，多个节点用英文逗号（,）分隔
      cluster-nodes: localhost:9300
  jackson:
    default-property-inclusion: non_null
index-entity:
  configs:
    - docCode: rail_way
      indexName: rail_way
      type: base
      documentPath: com.valten.model.RailWayDocument