server:
  port: 8083

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@192.168.40.104:1521:HCZZ
      username: syt
      password: syt
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/mybatis_plus2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#      username: root
#      password: 123456

mybatis-plus:
  configuration:
    cache-enabled: false
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  typeAliasesPackage: com.valten.model
  mapper-locations: classpath:mapper/*.xml
  global-config:
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    auto-set-db-type: true
    id-type: 2
